services:
  nginx:
    image: ghcr.io/mailu/nginx:2024.06.36
    restart: unless-stopped
    env_file: .env
    environment:
      - PORTS=25,80,443,465,587,993,995,4190
    networks:
      - default
      - traefik_default
    ports:
      - "25:25"
      - 587:587
      - 993:993
    volumes:
      - nginx:/certs
    labels:
      - traefik.enable=true
      - traefik.http.services.mail.loadbalancer.server.port=80
      - traefik.http.middlewares.mail.replacepathregex.regex=^/.well-known/(?:card|cal)dav
      - traefik.http.middlewares.mail.replacepathregex.replacement=/webdav
      - traefik.http.routers.mail.rule=Host(`mail.chamburr.com`)
      - traefik.http.routers.mail.service=mail
      - traefik.http.routers.mail.middlewares=mail
      - traefik.http.routers.mail.tls=true
      - traefik.http.routers.mail.tls.certresolver=letsencrypt
      - traefik.http.routers.mail.tls.domains[0].main=chamburr.com
      - traefik.http.routers.mail.tls.domains[0].sans=*.chamburr.com

  admin:
    image: ghcr.io/mailu/admin:2024.06.36
    restart: unless-stopped
    env_file: .env
    environment:
      - PORTS=25,80,443,465,587,993,995,4190
      - DKIM_PATH=/data/dkim/{domain}.key
    volumes:
      - admin:/data
    depends_on:
      - redis
      - unbound
    dns:
      - 172.16.0.254

  dovecot:
    image: ghcr.io/mailu/dovecot:2024.06.36
    restart: unless-stopped
    env_file: .env
    volumes:
      - dovecot:/mail
      - ${PWD}/dovecot.conf:/overrides/dovecot.conf:ro
    depends_on:
      - nginx
      - unbound
    dns:
      - 172.16.0.254

  postfix:
    image: ghcr.io/mailu/postfix:2024.06.36
    restart: unless-stopped
    env_file: .env
    volumes:
      - postfix:/queue
    depends_on:
      - nginx
      - unbound
    dns:
      - 172.16.0.254

  rspamd:
    image: ghcr.io/mailu/rspamd:2024.06.36
    hostname: rspamd
    restart: unless-stopped
    env_file: .env
    volumes:
      - rspamd:/var/lib/rspamd
      - ${PWD}/milter_headers.conf:/conf/milter_headers.conf:ro
    depends_on:
      - nginx
      - unbound
    dns:
      - 172.16.0.254

  unbound:
    image: ghcr.io/mailu/unbound:2024.06.36
    restart: unless-stopped
    env_file: .env
    networks:
      default:
        ipv4_address: 172.16.0.254

  radicale:
    image: ghcr.io/mailu/radicale:2024.06.36
    restart: unless-stopped
    volumes:
      - radicale:/data

  z-push:
    # yamllint disable-line rule:line-length
    image: docker.io/kour1er/z-push:latest@sha256:4a37f758b3799e746c6c2e8953c174017e37b0acfd6e64088084714829db7eae
    restart: unless-stopped
    entrypoint: []
    command:
      - /entrypoint.sh
    environment:
      - BACKEND_PROVIDER=BackendCombined
      - IMAP_FOLDER_ARCHIVE='Archive'
      - IMAP_FOLDER_DRAFTS='Drafts'
      - IMAP_FOLDER_INBOX='Inbox'
      - IMAP_FOLDER_SENT='Sent'
      - IMAP_FOLDER_SPAM='Junk'
      - IMAP_FOLDER_TRASH='Trash'
      - IMAP_PORT=993
      - IMAP_SERVER_METHOD=smtp
      - IMAP_SERVER=mail.chamburr.com
      - CALDAV_PATH=/webdav/calendars/%u/
      - CARDDAV_PATH=/webdav/addressbooks/%u/
      - TIMEZONE=Etc/UTC
      - ZPUSH_HOST=mail.chamburr.com
    networks:
      - default
      - traefik_default
    volumes:
      - z-push:/var/lib/z-push
      - ${PWD}/z-push/entrypoint.sh:/entrypoint.sh:ro
      - ${PWD}/z-push/config.php:/usr/share/z-push/backend/combined/config.php:ro
    labels:
      - traefik.enable=true
      - traefik.http.services.mail-push.loadbalancer.server.port=8080
      # yamllint disable-line rule:line-length
      - traefik.http.routers.mail-push.rule=Host(`mail.chamburr.com`) && PathPrefix(`/Microsoft-Server-ActiveSync`)
      - traefik.http.routers.mail-push.service=mail-push
      - traefik.http.routers.mail-push.tls=true
      - traefik.http.routers.mail-push.tls.certresolver=letsencrypt
      - traefik.http.routers.mail-push.tls.domains[0].main=chamburr.com
      - traefik.http.routers.mail-push.tls.domains[0].sans=*.chamburr.com

  redis:
    image: public.ecr.aws/docker/library/redis:7.4.2-alpine
    restart: unless-stopped
    volumes:
      - redis:/data

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16
  traefik_default:
    external: true

volumes:
  nginx:
  admin:
  dovecot:
  postfix:
  rspamd:
  radicale:
  z-push:
  redis:
