---
version: "3"

services:
  nginx:
    image: ghcr.io/mailu/nginx:2024.06.35
    restart: unless-stopped
    environment:
      - LD_PRELOAD=/usr/lib/libhardened_malloc.so
      - ADMIN_ADDRESS=admin
      - ANTISPAM_ADDRESS=rspamd
      - IMAP_ADDRESS=dovecot
      - SECRET_KEY=${SECRET}
      - TLS_FLAVOR=mail-letsencrypt
      - HOSTNAMES=mail.chamburr.com
      - PORTS=25,80,443,465,587,993,995,4190
      - MESSAGE_SIZE_LIMIT=104857600
      - POSTMASTER=hi
      - DOMAIN=chamburr.com
      - ADMIN=true
      - WEBDAV=none
      - WEBMAIL=none
      - WEBROOT_REDIRECT=/admin/
      - WEB_ADMIN=/admin
    networks:
      - default
      - traefik_default
    ports:
      - "25:25"
      - 587:587
      - 993:993
    volumes:
      - nginx:/certs
    labels:
      - traefik.enable=true
      - traefik.http.services.mail.loadbalancer.server.port=80
      - traefik.http.routers.mail.rule=Host(`mail.chamburr.com`)
      - traefik.http.routers.mail.service=mail
      - traefik.http.routers.mail.tls=true
      - traefik.http.routers.mail.tls.certresolver=letsencrypt
      - traefik.http.routers.mail.tls.domains[0].main=chamburr.com
      - traefik.http.routers.mail.tls.domains[0].sans=*.chamburr.com
    healthcheck:
      disable: true

  admin:
    image: ghcr.io/mailu/admin:2024.06.35
    restart: unless-stopped
    environment:
      - LD_PRELOAD=/usr/lib/libhardened_malloc.so
      - IMAP_ADDRESS=dovecot
      - REDIS_ADDRESS=redis
      - SMTP_ADDRESS=postfix
      - SUBNET=172.16.0.0/16
      - SECRET_KEY=${SECRET}
      - POSTMASTER=postmaster
      - DOMAIN=chamburr.com
      - HOSTNAMES=mail.chamburr.com
      - PORTS=25,80,443,465,587,993,995,4190
      - WEBMAIL=none
      - RECIPIENT_DELIMITER=+
      - DKIM_PATH=/data/dkim/{domain}.key
      - MESSAGE_RATELIMIT=200/hour
      - MESSAGE_RATELIMIT_EXEMPTION=
      - AUTH_RATELIMIT_IP=60/hour
      - AUTH_RATELIMIT_USER=100/day
      - DB_FLAVOR=sqlite
    volumes:
      - admin:/data
    healthcheck:
      disable: true
    depends_on:
      - redis

  dovecot:
    image: ghcr.io/mailu/dovecot:2024.06.35
    restart: unless-stopped
    environment:
      - LD_PRELOAD=/usr/lib/libhardened_malloc.so
      - ADMIN_ADDRESS=admin
      - ANTISPAM_ADDRESS=rspamd
      - FRONT_ADDRESS=nginx
      - SUBNET=172.16.0.0/16
      - SECRET_KEY=${SECRET}
      - POSTMASTER=postmaster
      - DOMAIN=chamburr.com
      - HOSTNAMES=mail.chamburr.com
      - RECIPIENT_DELIMITER=+
    volumes:
      - dovecot:/mail
      - ${PWD}/dovecot.conf:/overrides/dovecot.conf:ro
    healthcheck:
      disable: true
    depends_on:
      - nginx

  postfix:
    image: ghcr.io/mailu/postfix:2024.06.34
    restart: unless-stopped
    environment:
      - LD_PRELOAD=/usr/lib/libhardened_malloc.so
      - ADMIN_ADDRESS=admin
      - ANTISPAM_ADDRESS=rspamd
      - FRONT_ADDRESS=nginx
      - IMAP_ADDRESS=dovecot
      - SUBNET=172.16.0.0/16
      - SECRET_KEY=${SECRET}
      - REJECT_UNLISTED_RECIPIENT=yes
      - DOMAIN=chamburr.com
      - HOSTNAMES=mail.chamburr.com
      - MESSAGE_SIZE_LIMIT=104857600
      - RECIPIENT_DELIMITER=+
      - RELAYHOST=${RELAY_HOST}:${RELAY_PORT}
      - RELAYUSER=${RELAY_USERNAME}
      - RELAYPASSWORD=${RELAY_PASSWORD}
    volumes:
      - postfix:/queue
    healthcheck:
      disable: true
    depends_on:
      - nginx

  rspamd:
    image: ghcr.io/mailu/rspamd:2024.06.34
    hostname: rspamd
    restart: unless-stopped
    environment:
      - LD_PRELOAD=/usr/lib/libhardened_malloc.so
      - ADMIN_ADDRESS=admin
      - REDIS_ADDRESS=redis
      - SUBNET=172.16.0.0/16
      - SECRET_KEY=${SECRET}
    volumes:
      - rspamd:/var/lib/rspamd
      - ${PWD}/milter_headers.conf:/conf/milter_headers.conf:ro
    healthcheck:
      disable: true
    depends_on:
      - nginx

  redis:
    image: redis:7.4.2-alpine
    restart: unless-stopped
    volumes:
      - redis:/data

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16
  traefik_default:
    external: true

volumes:
  nginx:
  admin:
  dovecot:
  postfix:
  rspamd:
  redis:
