services:
  nginx:
    image: ghcr.io/mailu/nginx:2024.06.43
    restart: unless-stopped
    env_file: .env
    environment:
      - PORTS=25,80,443,465,587,993,995,4190
    networks:
      - default
      - traefik_default
    ports:
      - "25:25"
      - 587:587
      - 993:993
    volumes:
      - nginx:/certs
    healthcheck:
      disable: true
    labels:
      - traefik.enable=true
      - traefik.http.services.mail.loadbalancer.server.port=80
      - traefik.http.routers.mail.rule=Host(`mail.chamburr.com`)
      - traefik.http.routers.mail.service=mail
      - traefik.http.routers.mail.tls=true
      - traefik.http.routers.mail.tls.certresolver=letsencrypt
      - traefik.http.routers.mail.tls.domains[0].main=chamburr.com
      - traefik.http.routers.mail.tls.domains[0].sans=*.chamburr.com

  admin:
    image: ghcr.io/mailu/admin:2024.06.44
    restart: unless-stopped
    env_file: .env
    environment:
      - PORTS=25,80,443,465,587,993,995,4190
      - DKIM_PATH=/data/dkim/{domain}.key
    volumes:
      - admin:/data
    depends_on:
      - redis
      - unbound
    dns:
      - 172.16.0.254
    healthcheck:
      disable: true

  dovecot:
    image: ghcr.io/mailu/dovecot:2024.06.43
    restart: unless-stopped
    env_file: .env
    volumes:
      - dovecot:/mail
      - ${PWD}/dovecot.conf:/overrides/dovecot.conf:ro
    depends_on:
      - nginx
      - unbound
    dns:
      - 172.16.0.254
    healthcheck:
      disable: true

  postfix:
    image: ghcr.io/mailu/postfix:2024.06.43
    restart: unless-stopped
    env_file: .env
    volumes:
      - postfix:/queue
    depends_on:
      - nginx
      - unbound
    dns:
      - 172.16.0.254
    healthcheck:
      disable: true

  rspamd:
    image: ghcr.io/mailu/rspamd:2024.06.43
    hostname: rspamd
    restart: unless-stopped
    env_file: .env
    volumes:
      - rspamd:/var/lib/rspamd
      - ${PWD}/milter_headers.conf:/conf/milter_headers.conf:ro
    depends_on:
      - nginx
      - unbound
    dns:
      - 172.16.0.254
    healthcheck:
      disable: true

  unbound:
    image: ghcr.io/mailu/unbound:2024.06.43
    restart: unless-stopped
    env_file: .env
    networks:
      default:
        ipv4_address: 172.16.0.254
    healthcheck:
      disable: true

  radicale:
    image: ghcr.io/mailu/radicale:2024.06.43
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - /app/venv/bin/pip install -U radicale && radicale -S -C /radicale.conf
    volumes:
      - radicale:/data
    healthcheck:
      disable: true

  redis:
    image: docker.io/library/redis:8.2.2-alpine
    restart: unless-stopped
    volumes:
      - redis:/data

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16
  traefik_default:
    external: true

volumes:
  nginx:
  admin:
  dovecot:
  postfix:
  rspamd:
  radicale:
  zpush:
  redis:
