---
- name: Remove snap
  community.general.snap:
    name: "{{ item }}"
    state: absent
  loop: "{{ remove_snap }}"
  register: common_snap_remove
  failed_when:
    - common_snap_remove.failed
    - "'Failed to find required executable' not in common_snap_remove.msg"

- name: Delete snap directory
  ansible.builtin.file:
    path: /root/snap
    state: absent

- name: Remove packages
  ansible.builtin.apt:
    name: "{{ remove_packages }}"
    purge: true
    state: absent

- name: Install packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    update_cache: true
    state: present

- name: Install auto upgrade package
  ansible.builtin.apt:
    name: unattended-upgrades
    update_cache: true
    state: present

- name: Copy auto upgrade configuration
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/apt/apt.conf.d/{{ item }}
    owner: root
    group: root
    mode: 0644
  loop:
    - 20auto-upgrades
    - 50unattended-upgrades

- name: Enable auto upgrade service
  ansible.builtin.service:
    name: unattended-upgrades
    enabled: true
    state: started
