services:
  helper:
    # yamllint disable-line rule:line-length
    image: ghcr.io/chamburr/modmail-helper:latest@sha256:3d24d9a403bdc45299bb5720a79d166182d674e00674c88e4d254af322ff8ddd
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - printenv CONFIG > /app/config.json && yarn start
    environment:
      - CONFIG=${CONFIG}
