services:
  helper:
    # yamllint disable-line rule:line-length
    image: ghcr.io/chamburr/modmail-helper:latest@sha256:77256f209db6bd578bc25b7f622b1de396846ceece22b3b39b86d6b7a8cb0edb
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - printenv CONFIG > /app/config.json && yarn start
    environment:
      - CONFIG=${CONFIG}
