---
version: "3"

services:
  ghost:
    image: ghost:5.85.2-alpine
    restart: unless-stopped
    environment:
      - url=https://blog.chamburr.com
      - database__client=mysql
      - database__connection__host=mysql
      - database__connection__port=3306
      - database__connection__user=root
      - database__connection__password=
      - database__connection__database=ghost
      - mail__transport=SMTP
      - mail__from=${MAIL_SENDER}
      - mail__options__service=Custom
      - mail__options__host=${MAIL_HOST}
      - mail__options__port=${MAIL_PORT}
      - mail__options__secure=false
      - mail__options__auth__user=${MAIL_USERNAME}
      - mail__options__auth__pass=${MAIL_PASSWORD}
      - logging__level=info
      - logging__transports=["stdout"]
    networks:
      - default
      - traefik_default
    volumes:
      - ghost:/var/lib/ghost/content
    labels:
      - traefik.enable=true
      - traefik.http.services.blog.loadbalancer.server.port=2368
      - traefik.http.routers.blog.rule=Host(`blog.chamburr.com`)
      - traefik.http.routers.blog.service=blog
      - traefik.http.routers.blog.tls=true
      - traefik.http.routers.blog.tls.certresolver=letsencrypt
      - traefik.http.routers.blog.tls.domains[0].main=chamburr.com
      - traefik.http.routers.blog.tls.domains[0].sans=*.chamburr.com

  mysql:
    image: mysql:8.4.0
    restart: unless-stopped
    command:
      - --performance-schema=OFF
    environment:
      - MYSQL_DATABASE=ghost
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mysql:/var/lib/mysql

networks:
  traefik_default:
    external: true

volumes:
  ghost:
  mysql:
