---
- name: Install backup package
  ansible.builtin.apt:
    name: rclone
    update_cache: true
    state: present

- name: Create backup config
  ansible.builtin.command:
    cmd: >
      rclone --config /etc/rclone/rclone.conf config create minio s3 provider Minio
      endpoint {{ lookup('env', 'MINIO_ENDPOINT') }}
      access_key_id {{ lookup('env', 'MINIO_ACCESS_KEY') }}
      secret_access_key {{ lookup('env', 'MINIO_SECRET_KEY') }}
    creates: /etc/rclone/rclone.conf
  when:
    - lookup('env', 'MINIO_ENDPOINT') is defined
    - lookup('env', 'MINIO_ACCESS_KEY') is defined
    - lookup('env', 'MINIO_SECRET_KEY') is defined

- name: Add cron for purge
  ansible.builtin.cron:
    name: Purge backup
    minute: "0"
    hour: "0"
    user: "{{ username }}"
    job: >-
      sudo rclone --config /etc/rclone/rclone.conf purge
      "minio:elements/_old/{{ inventory_hostname }}/$(date -d '7 day ago' +%F)"
    state: present

- name: Add cron for files
  ansible.builtin.cron:
    name: Backup files
    minute: "5"
    hour: "0"
    user: "{{ username }}"
    job: >-
      sudo rclone --config /etc/rclone/rclone.conf sync
      /var/lib/docker/volumes minio:elements/{{ inventory_hostname }} --s3-no-check-bucket
      --backup-dir "minio:elements/_old/{{ inventory_hostname }}/$(date +%F)"
    state: present
