---
- name: Add netmaker key
  ansible.builtin.shell: # noqa: command-instead-of-module
    cmd: |
      set -o pipefail && curl -s https://apt.netmaker.org/gpg.key \
        | gpg --dearmor > /usr/share/keyrings/netmaker.gpg
    creates: /usr/share/keyrings/netmaker.gpg

- name: Add netmaker repository
  ansible.builtin.apt_repository:
    filename: netmaker
    repo: deb [signed-by=/usr/share/keyrings/netmaker.gpg] https://apt.netmaker.org stable main
    state: present

- name: Install netmaker packages
  ansible.builtin.apt:
    name:
      - netclient
      - wireguard-tools
    update_cache: true
    state: present

- name: Enable netmaker service
  ansible.builtin.service:
    name: netclient
    enabled: true
    state: started

- name: Join netmaker network
  ansible.builtin.command:
    cmd: netclient join -t {{ lookup('env', 'NETMAKER_TOKEN') }}
    creates: /etc/netclient/netclient.json
  when: lookup('env', 'NETMAKER_TOKEN') is defined
