---
version: "3"

services:
  wiki:
    image: ghcr.io/requarks/wiki:2.5.296
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - sed -i -E 's/(.+)updateUser\(\{/        if (context.req.user.id === 4) return
        graphHelper.generateError(new Error("BIG BROTHER IS WATCHING YOU!"))\n\n\1updateUser({/'
        /wiki/server/graph/resolvers/user.js && node server
    environment:
      - DB_TYPE=mariadb
      - DATABASE_URL=mysql://root@mariadb:3306/wiki
    networks:
      - default
      - traefik_default
    labels:
      - traefik.enable=true
      - traefik.http.services.wjfclass.loadbalancer.server.port=3000
      - traefik.http.routers.wjfclass.rule=Host(`wjfclass.net`, `www.wjfclass.net`)
      - traefik.http.routers.wjfclass.service=wjfclass
      - traefik.http.routers.wjfclass.middlewares=redirect
      - traefik.http.routers.wjfclass.tls=true
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.10.3
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=wiki
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
    volumes:
      - mariadb:/var/lib/mysql

networks:
  traefik_default:
    external: true

volumes:
  mariadb:
