---
version: "3"

services:
  wiki:
    image: requarks/wiki:2.5.295
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - sed -E 's/(.+)updateUser\(\{/        if (context.req.user.id === 4) return
        graphHelper.generateError(new Error("BIG BROTHER IS WATCHING YOU!"))\n\n\1updateUser({/'
        /wiki/server/graph/resolvers/user.js && node server
    environment:
      - DB_TYPE=mariadb
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=
      - DB_NAME=wiki
    networks:
      - default
      - traefik_default
    labels:
      - traefik.enable=true
      - traefik.http.services.wjfclass.loadbalancer.server.port=3000
      - traefik.http.routers.wjfclass.rule=Host(`wjfclass.net`, `www.wjfclass.net`)
      - traefik.http.routers.wjfclass.service=wjfclass
      - traefik.http.routers.wjfclass.middlewares=redirect@docker
      - traefik.http.routers.wjfclass.tls=true
      - traefik.http.routers.wjfclass.tls.certresolver=letsencrypt
      - traefik.http.routers.blog.tls.domains[0].main=wjfclass.net
      - traefik.http.routers.blog.tls.domains[0].sans=*.wjfclass.net
    depends_on:
      - postgres

  mariadb:
    image: mariadb:10.10.2
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=wiki
      - MARIADB_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mariadb:/var/lib/mysql

networks:
  traefik_default:
    external: true

volumes:
  mariadb:
