---
version: "3"

services:
  templates:
    image: >-
      chamburr/discord-templates:latest@sha256:7f3c13915dfd95c2967859daea3d94983050347587349f0bb1e92f3e34e2aaec
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - printenv CONFIG > /app/config.json && yarn start
    environment:
      - CONFIG=${CONFIG}
    networks:
      - default
      - traefik_default
    volumes:
      - templates:/data
    labels:
      - traefik.enable=true
      - traefik.http.services.templates.loadbalancer.server.port=8080
      - traefik.http.routers.templates.rule=Host(`discordtemplates.me`, `www.discordtemplates.me`)
      - traefik.http.routers.templates.service=templates
      - traefik.http.routers.templates.middlewares=redirect
      - traefik.http.routers.templates.tls=true
      - traefik.http.routers.templates.tls.certresolver=letsencrypt
      - traefik.http.routers.templates.tls.domains[0].main=discordtemplates.me
      - traefik.http.routers.templates.tls.domains[0].sans=*.discordtemplates.me

networks:
  traefik_default:
    external: true

volumes:
  templates:
