---
version: "3"

services:
  templates:
    # yamllint disable-line rule:line-length
    image: chamburr/discord-templates:latest@sha256:4cfaf97132ccb28fbb7fdf18c105d5e38d09414ddf98b39106f3cdca9b022f99
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - printenv CONFIG > /app/config.json && yarn start
    environment:
      - CONFIG=${CONFIG}
    networks:
      - default
      - traefik_default
    volumes:
      - templates:/data
    labels:
      - traefik.enable=true
      - traefik.http.services.discord-templates.loadbalancer.server.port=8080
      # yamllint disable-line rule:line-length
      - traefik.http.routers.discord-templates.rule=Host(`discordtemplates.me`, `www.discordtemplates.me`)
      - traefik.http.routers.discord-templates.service=discord-templates
      - traefik.http.routers.discord-templates.middlewares=redirect
      - traefik.http.routers.discord-templates.tls=true
      - traefik.http.routers.discord-templates.tls.certresolver=letsencrypt
      - traefik.http.routers.discord-templates.tls.domains[0].main=discordtemplates.me
      - traefik.http.routers.discord-templates.tls.domains[0].sans=*.discordtemplates.me

networks:
  traefik_default:
    external: true

volumes:
  templates:
