---
version: "3"

services:
  templates:
    image: >-
      chamburr/discord-templates:latest@sha256:54c40767fb17a58dc7dfd499bd7c6a7accd3eca33b32cac6499572e052f4dd46
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - printenv CONFIG > /app/config.json && yarn start
    environment:
      - CONFIG=${CONFIG}
    networks:
      - default
      - traefik_default
    volumes:
      - templates:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.templates.rule=Host(`discordtemplates.me`)
      - traefik.http.routers.templates.service=templates-service
      - traefik.http.services.templates-service.loadbalancer.server.port=8080
      - traefik.http.routers.templates.tls=true
      - traefik.http.routers.templates.tls.certresolver=letsencrypt

networks:
  traefik_default:
    external: true

volumes:
  templates:
