---
version: "3"

services:
  helper:
    # yamllint disable-line rule:line-length
    image: chamburr/modmail-helper:latest@sha256:17c460c055ebed35c7f4e62e2850efed3449f2fb100e9bee6e54d962cf94e055
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - printenv CONFIG > /app/config.json && yarn start
    environment:
      - CONFIG=${CONFIG}
