---
- name: Disable dns service
  ansible.builtin.service:
    name: systemd-resolved
    enabled: false
    state: stopped

- name: Delete dns from ifupdown
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/network/if-up.d/resolved
    - /etc/network/if-down.d/resolved

- name: Copy resolv configuration
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
