---
version: "3"

services:
  node:
    image: node:21.4.0-alpine
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - npm install -g miniflare@2 && miniflare /app/worker.js
    environment:
      - SECRET=${SECRET}
    networks:
      - default
      - traefik_default
    expose:
      - "8787"
    volumes:
      - ${PWD}/worker.js:/app/worker.js
    labels:
      - traefik.enable=true
      - traefik.http.services.notes.loadbalancer.server.port=8787
      - traefik.http.routers.notes.rule=Host(`notes.chamburr.com`)
      - traefik.http.routers.notes.service=notes
      - traefik.http.routers.notes.tls=true
      - traefik.http.routers.notes.tls.certresolver=letsencrypt
      - traefik.http.routers.notes.tls.domains[0].main=chamburr.com
      - traefik.http.routers.notes.tls.domains[0].sans=*.chamburr.com

networks:
  traefik_default:
    external: true
