---
dns_servers:
  - 1.1.1.1
  - 1.0.0.1

fail2ban_ban_action: iptables-allports
fail2ban_max_retry: 3
fail2ban_find_time: 600
fail2ban_ban_time: 86400
fail2ban_ignore_ip:
  - 10.0.0.0/8

firewall_services:
  22/tcp: allow
  80/tcp: allow
  443/tcp: allow
  51820/udp: allow

ssh_password: "no"
ssh_root: "no"
