---
version: "3"

services:
  chamburr:
    image: >-
      chamburr/chamburr.com:latest@sha256:8c004adb2db461bd36fedb69a159d5a1aef379725a99b78b22906caffe1312be
    restart: unless-stopped
    networks:
      - default
      - traefik_default
    labels:
      - traefik.enable=true
      - traefik.http.services.homepage.loadbalancer.server.port=80
      - traefik.http.routers.homepage.rule=Host(`chamburr.com`, `www.chamburr.com`)
      - traefik.http.routers.homepage.service=homepage
      - traefik.http.routers.homepage.middlewares=redirect
      - traefik.http.routers.homepage.tls=true
      - traefik.http.routers.homepage.tls.certresolver=letsencrypt
      - traefik.http.routers.homepage.tls.domains[0].main=chamburr.com
      - traefik.http.routers.homepage.tls.domains[0].sans=*.chamburr.com

networks:
  traefik_default:
    external: true
