---
version: "3"

services:
  chamburr:
    image: >-
      chamburr/chamburr.com:latest@sha256:8c004adb2db461bd36fedb69a159d5a1aef379725a99b78b22906caffe1312be
    restart: unless-stopped
    networks:
      - default
      - traefik_default
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`chamburr.com`)
      - traefik.http.routers.homepage.service=homepage-service
      - traefik.http.services.homepage-service.loadbalancer.server.port=80
      - traefik.http.routers.homepage.tls=true
      - traefik.http.routers.homepage.tls.certresolver=letsencrypt

networks:
  traefik_default:
    external: true
