services:
  chamburr:
    # yamllint disable-line rule:line-length
    image: ghcr.io/chamburr/chamburr.com:latest@sha256:902ea761dcbdac67f62ccb2fa5a7ef946a43910a6879902d59911a4bf2e66cf3
    restart: unless-stopped
    networks:
      - default
      - traefik_default
    labels:
      - traefik.enable=true
      - traefik.http.services.home.loadbalancer.server.port=80
      - traefik.http.routers.home.rule=Host(`chamburr.com`) || Host(`www.chamburr.com`)
      - traefik.http.routers.home.service=home
      - traefik.http.routers.home.middlewares=redirect
      - traefik.http.routers.home.tls=true
      - traefik.http.routers.home.tls.certresolver=letsencrypt
      - traefik.http.routers.home.tls.domains[0].main=chamburr.com
      - traefik.http.routers.home.tls.domains[0].sans=*.chamburr.com

networks:
  traefik_default:
    external: true
