- name: Add docker key
  ansible.builtin.shell: # noqa: command-instead-of-module
    cmd: |
      set -o pipefail && curl -s https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor \
        > /usr/share/keyrings/docker.gpg
    creates: /usr/share/keyrings/docker.gpg

- name: Add docker repository
  ansible.builtin.apt_repository:
    filename: docker
    repo: >-
      deb [signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu
      jammy stable
    state: present

- name: Install docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: true
    state: present

- name: Install docker compose package
  ansible.builtin.apt:
    name: docker-compose-plugin
    update_cache: true
    state: present

- name: Enable docker service
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - docker
    - containerd

- name: Add docker credentials
  community.docker.docker_login:
    username: "{{ lookup('env', 'DOCKER_USERNAME') }} "
    password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"
