- name: Create docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add docker group to user
  ansible.builtin.user:
    name: "{{ common_username }}"
    groups: docker
    append: yes

- name: Add docker key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: 0644

- name: Add docker repository
  ansible.builtin.apt_repository:
    filename: docker
    repo: >-
      deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Install docker packages
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Install docker compose package
  ansible.builtin.package:
    name: docker-compose-plugin
    state: present

- name: Enable docker service
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - docker
    - containerd

- name: Add docker credentials
  community.docker.docker_login:
    username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
    password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"
  become: false
  when: lookup('env', 'DOCKER_USERNAME') is defined
