---
- name: Clone repository
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: "{{ git_repository }}"
    version: "{{ git_branch }}"
    dest: /home/{{ username }}/{{ git_name }}
    update: false
