- name: Clone repository
  ansible.builtin.git:
    repo: "{{ docker_git_repository }}"
    version: "{{ docker_git_branch }}"
    dest: /home/{{ common_username }}/{{ docker_git_name }}
    update: false
  become: false
