- name: Add sops key
  ansible.builtin.get_url:
    url: https://dl.cloudsmith.io/public/cloudposse-dev/packages/gpg.key
    dest: /etc/apt/keyrings/sops.asc
    mode: 0644

- name: Add sops repository
  ansible.builtin.apt_repository:
    filename: sops
    repo: >-
      deb [signed-by=/etc/apt/keyrings/sops.asc]
      https://dl.cloudsmith.io/public/cloudposse-dev/packages/deb/ubuntu jammy main
    state: present

- name: Install sops package
  ansible.builtin.package:
    name: sops
    state: present
