- name: Add sops key
  ansible.builtin.shell: # noqa: command-instead-of-module
    cmd: |
      set -o pipefail && curl -s https://dl.cloudsmith.io/public/cloudposse/packages/gpg.key \
        | gpg --dearmor > /etc/apt/keyrings/sops.gpg
    creates: /etc/apt/keyrings/sops.gpg

- name: Add sops repository
  ansible.builtin.apt_repository:
    filename: sops
    repo: >-
      deb [signed-by=/etc/apt/keyrings/sops.gpg]
      https://dl.cloudsmith.io/public/cloudposse/packages/deb/ubuntu jammy main
    state: present

- name: Install sops package
  ansible.builtin.package:
    name: sops
    state: present
