---
kind: pipeline
name: docker

steps:
  - name: run deploy script
    image: python
    commands:
      - pip install ansible
      - echo "USER=chamburr" > .env
      - echo "$SSH_PRIVATE_KEY" > /tmp/id_ed25519
      - chmod 400 /tmp/id_ed25519
      - ./scripts/ansible.sh all -a "chdir=/home/chamburr/elements
        /bin/sh -c 'git fetch --prune && git reset --hard origin/main && git clean -xdf &&
        AGE_KEY=$AGE_KEY AGE_RECIPIENTS=$AGE_RECIPIENTS ./scripts/deploy.sh'"
    environment:
      ANSIBLE_FORCE_COLOR: true
      ANSIBLE_HOST_KEY_CHECKING: false
      ANSIBLE_PRIVATE_KEY_FILE: /tmp/id_ed25519
      SSH_PRIVATE_KEY:
        from_secret: ssh_private_key
      AGE_KEY:
        from_secret: age_key
      AGE_RECIPIENTS:
        from_secret: age_recipients

trigger:
  event:
    - push
  branch:
    - main
  paths:
    - ansible/hosts.yml
    - common/**/*
    - radon/**/*
    - xenon/**/*
    - krypton/**/*
    - argon/**/*
    - neon/**/*
    - helium/**/*
