---
kind: pipeline
name: lint

steps:
  - name: lint yaml
    image: python
    commands:
      - pip install yamllint
      - yamllint .
  - name: lint ansible
    image: python
    commands:
      - pip install ansible-lint
      - ansible-lint ansible -q

trigger:
  event:
    - push
  branch:
    - main
