when:
  - event: push
    branch: main
    path:
      - ansible/hosts.yml
      - common/**
      - radon/**
      - xenon/**
      - krypton/**
      - argon/**
      - neon/**
      - helium/**

steps:
  - name: run deploy script
    image: python
    commands:
      - pip install ansible
      - echo "$SSH_PRIVATE_KEY" > /tmp/id_ed25519
      - chmod 400 /tmp/id_ed25519
      - ansible all -a "chdir=/home/chamburr/elements /bin/sh -c 'git fetch --prune &&
        git reset --hard origin/main && git clean -xdf && SOPS_KEY=$SOPS_KEY
        SOPS_RECIPIENTS=$SOPS_RECIPIENTS ./scripts/deploy.sh'"
    environment:
      ANSIBLE_FORCE_COLOR: true
      ANSIBLE_HOST_KEY_CHECKING: false
      ANSIBLE_PRIVATE_KEY_FILE: /tmp/id_ed25519
      SSH_PRIVATE_KEY:
        from_secret: ssh_private_key
      SOPS_KEY:
        from_secret: sops_key
      SOPS_RECIPIENTS:
        from_secret: sops_recipients
